/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#define _GNU_SOURCE
#include <ncurses.h>

#include "rpcchat.h"
#include <stdio.h>
#include <stdlib.h>

enum _MyBool {_false=0, _true=1};

int get_option() {
    printf("\nSelect one option:\n\t1- Write\n\t2- Read chat\n\t3- Exit\n");
    int option;

    scanf("%d", &option);

    return option;
}

enum _MyBool invalid_option(int option) {
    enum _MyBool invalid = (option > 3 || option < 1);

    return invalid;
}

void write_chat(CLIENT* clnt) {
    status  *result_1;
    char * write_0_arg = NULL;
    size_t len = 0;
    char aux;

    printf("Insert text: ");
    fflush(stdout);
    fflush(stdin);
    getline(&write_0_arg, &len, stdin);  // read enter (\n)
    getline(&write_0_arg, &len, stdin);  // read line

    printf("%s", write_0_arg);
    result_1 = write_0(&write_0_arg, clnt);
    if (result_1 == (status *) NULL) {
        clnt_perror (clnt, "call failed");
    }

    free(write_0_arg);
}

void read_chat(CLIENT* clnt) {
    char * *result_2;
    char *getchat_0_arg;

    result_2 = getchat_0((void*)&getchat_0_arg, clnt);
    if (result_2 == (char **) NULL) {
        clnt_perror (clnt, "call failed");
    }

    printf("chat: \n%s",*result_2);
}

void exit_chat(CLIENT* clnt) {

}

void
rpcchat_0(char *host)
{
    CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, rpcchat, rpcchat_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    int option = 1;
    void (*menu[])(CLIENT*) = {write_chat, read_chat, exit_chat};
    printf("hi\n");

    while(option != 3) {
        option = get_option();
        if(invalid_option(option))
            continue;

        (*menu[option-1])(clnt);
    }


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	// NCURSES TEST
    initscr();			        /* Start curses mode 		        */
    printw("Hello World !!!");	/* Print Hello World		        */
    refresh();			        /* Print it on to the real screen   */
    getch();			        /* Wait for user input              */
    endwin();			        /* End curses mode		            */

    host = argv[1];
    printf("hi\n");
    rpcchat_0 (host);
    exit (0);
}
