/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcchat.h"

bool_t
xdr_status (XDR *xdrs, status *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
