/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#define _GNU_SOURCE
#include <ncurses.h>

#include "rpcchat.h"
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <unistd.h>

/* Global variables */
WINDOW *output_win, *input_win;
CLIENT *clnt;
char *username = 0, *username_out = 0;
/* End of Global variables */

enum _MyBool {_false=0, _true=1};

void write_chat(CLIENT* clnt, char * line) {
    status  *result_1;
     char * write_0_arg = NULL;
    size_t len = 0;
    char aux;

    int line_size = sizeof(username) + sizeof(line);
    write_0_arg = (char*) malloc(sizeof(char*) * (line_size+1));
    strcpy(write_0_arg, username_out);
    strcat(write_0_arg, line);
    strcat(write_0_arg, "\n");
    //    write_0_arg[line_size+1] = '\0';
    //    write_0_arg[line_size+2] = '\0';
    result_1 = write_0(&write_0_arg, clnt);
    if (result_1 == (status *) NULL) {
        clnt_perror (clnt, "call failed");
    }

     free(write_0_arg);
}

char* read_chat(CLIENT* clnt) {
    char * *result_2;
    char *getchat_0_arg;

    result_2 = getchat_0((void*)&getchat_0_arg, clnt);
    if (result_2 == (char **) NULL) {
        clnt_perror (clnt, "call failed oopsie");
    }

    return *result_2;
}

void exit_chat(CLIENT* clnt) {

}

WINDOW *create_newwin(int height, int width, int starty, int startx)
{
    WINDOW *local_win;
    local_win = newwin(height, width, starty, startx);
    box(local_win, 0 , 0);		/* 0, 0 gives default characters
					   for the vertical and horizontal
					    lines			*/
    wrefresh(local_win);		/* Show that box 		*/
    return local_win;
}

void draw_chat() ;
void chat() ;
void *print_output(void *vargp);
void *get_input(void *vargp);

void
rpcchat_0(char *host)
{
#ifndef	DEBUG
	clnt = clnt_create (host, rpcchat, rpcchat_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    printf("hi\n");

    // getchar();
    draw_chat();
    chat(clnt);
    getch();
    endwin();

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 3) {
		printf ("usage: %s <server_host> <username>\n", argv[0]);
		exit (1);
	}

    host = argv[1];
	username = argv[2];
	username_out = malloc(sizeof username_out * sizeof username + 2);
	username_out = strcpy(username_out, argv[2]);
	username_out = strcat(username_out, ": ");

    rpcchat_0 (host);
    exit (0);
}

void draw_chat() {
    int startx, starty, width, height;
    // Start ncurses mode
    initscr();

    // Getting terminal size
    getmaxyx(stdscr,height, width);
    starty = 0;
    startx = 0;

    // Output window
    output_win = newwin(height-3, width, starty, startx);
    leaveok(output_win, TRUE);
    scrollok(output_win, TRUE);
    // Input window
    input_win  = newwin(2, width, height-1, startx);
}

void chat(CLIENT* clnt) {
    char buf[100] = {0}, chat[100] = {0}, *s = buf;
    int ch, cnt = 0, n = 1;
    WINDOW *w;

    if ((w = initscr()) == NULL) {
        fprintf(stderr, "Error: initscr()\n");
        exit(EXIT_FAILURE);
    }
    keypad(stdscr, TRUE);
    //noecho();
    //cbreak();      // disable line-buffering
    timeout(100);  // wait 100 milliseconds for input
    pthread_t output_thread_id;
    pthread_create(&output_thread_id, NULL, print_output, NULL);

    while (n != 0) {
        // refreshing the chat input:
        werase(input_win);
        wprintw(input_win, "%s --> %s", username, buf);
        wrefresh(input_win);
        // getch (with cbreak and timeout as above)
        // waits 100ms and returns ERR if it doesn't read anything.
        if ((ch = wgetch(input_win)) != ERR) {
            if (ch == '\n') {
                *s = 0;
                sscanf(buf, " %[^\n]s", chat);
                write_chat(clnt, chat);
                s = buf;
                *s = 0;
            }
            else if (ch == KEY_BACKSPACE || ch == 127 || ch == '\b') {
                int size = strlen(buf); //Total size of string
                buf[size-1] = '\0';
                if (s > buf)
                    *--s = 0;
            }
            else if (s - buf < (long)sizeof buf - 1) {
                *s++ = ch;
                *s = 0;
            }
        }
    }

    delwin(w);
    endwin();
    return;
}

void *print_output(void* vargp) {
    char * chat = 0;
    int it = 0;
    while(1){
        sleep(1);
        chat = read_chat(clnt);
        werase(output_win);
        //draw_chat();
        mvwprintw(output_win, 2, 2, "chat: \n%s", chat);
        wrefresh(output_win);
    }

}